Repository techit-plus-FE/my-parking-app, pull requests merged in 2024-01, with the labels that each got.

#193 customAxios Slice 생성, myPageSlice에 적용
  src/store/MyPageSlice.tsx
  src/store/customAxiosSlice.tsx
  src/store/index.ts
  src/types/customAxios.d.ts
Labels: 🪓버그수정, ⚒️코드 수정

#194 Reply , Purchase, Login 작업
  .env
  .env.development
  .env.production
  index.html
  src/components/UI/CommonButton.tsx
  src/components/domain/auth/Login.tsx
  src/components/domain/order-history/detail/OrderHistoryDetailList.tsx
  src/components/domain/order-history/ordercard/OrderCard.tsx
  src/components/domain/purchase/PaymentMethod.tsx
  src/components/domain/purchase/Purchase.tsx
  src/components/domain/purchase/PurchaseForm.tsx
  src/components/domain/purchase/PurchaseResult.module.css
  src/components/domain/purchase/PurchaseResult.tsx
  src/store/authSlice.tsx
  src/types/auth.d.ts
  src/types/purchase.d.ts
Labels: ⌨️기능 추가

#196 Map, Router 리팩토링 사항
  .gitignore
  src/App.tsx
  src/components/common/Error.tsx
  src/components/common/map/MainKakaoMap.tsx
  src/components/domain/product/detail/SellerInfoComponent.module.css
  src/components/domain/product/detail/SellerInfoComponent.tsx
  src/router/layouts/LayoutRoute.tsx
  src/router/layouts/PrivateRoute.tsx
  src/router/layouts/RootLayout.tsx
  src/router/layouts/UserTypeRoute.tsx
Labels: 🪓버그수정, 💡리팩토링, ⚒️코드 수정

#197 Store를 slice단위로 구독하기
  src/components/domain/auth/SignUpForm.tsx
  src/store/index.ts
Labels: 💡리팩토링, ⚒️코드 수정

#198 [SignUp] SignUp을 form-container 패턴으로 리팩토링
  src/components/domain/auth/SignUp.tsx
  src/components/domain/auth/SignUpForm.module.css
  src/components/domain/auth/SignUpForm.tsx
  src/pages/auth/SignUpPage.tsx
Labels: 🖌️마크업/UI, 💡리팩토링, ⚒️코드 수정

#201 마이페이지 리팩토링
  src/components/domain/my-services/MyProfile.tsx
Labels: 💡리팩토링, ⚒️코드 수정
